"""Unit tests for algebraic K-theory invariants, specifically Whitehead groups.

Overview:
    This suite validates the computation of Whitehead groups Wh(π₁) for various 
    fundamental groups. It covers trivial groups, cyclic groups, and ensures 
    that the rank formulas for Wh(C_n) match known mathematical values.

Key Concepts:
    - **Whitehead Group (Wh(G))**: The quotient of K₁(ℤG) by ±G.
    - **Whitehead Torsion**: The obstruction to a homotopy equivalence being a simple homotopy equivalence.
    - **Cyclic Whitehead Rank**: Dirichlet's Unit Theorem applied to the units of ℤ[ζ_n].
"""
from pysurgery.core.k_theory import compute_whitehead_group, cyclic_whitehead_rank
from pysurgery.core.fundamental_group import FundamentalGroup


def test_compute_whitehead_group_trivial():
    """Verify that the Whitehead group of the trivial group is trivial.

    What is Being Computed?:
        Wh({1}) = K₁(ℤ) / {±1} = {±1} / {±1} = 0.

    Preserved Invariants:
        - Whitehead rank (0).
    """
    pi_1 = FundamentalGroup(generators=[], relations=[])
    wg = compute_whitehead_group(pi_1)
    assert wg.rank == 0
    assert wg.computable
    assert wg.exact


def test_compute_whitehead_group_circle():
    """Verify that Wh(ℤ) is trivial (Bass-Heller-Swan).

    What is Being Computed?:
        The Whitehead group of the infinite cyclic group (π₁ of a circle).

    Algorithm:
        1. Create a FundamentalGroup with one generator and no relations.
        2. Compute the Whitehead group.
        3. Assert rank is 0.
    """
    pi_1 = FundamentalGroup(generators=["g_0"], relations=[])
    wg = compute_whitehead_group(pi_1)
    assert wg.rank == 0
    assert wg.computable
    assert wg.exact
    assert "Wh(Z) = 0" in wg.description


def test_compute_whitehead_group_Z5():
    """Verify the rank of the Whitehead group for the cyclic group C₅.

    What is Being Computed?:
        Wh(C₅), which has rank 1 (generated by the unit 1 - t - t⁻¹ in ℤ[C₅]).

    Algorithm:
        1. Create a FundamentalGroup for C₅ (one generator, relation g⁵=1).
        2. Compute the Whitehead group.
        3. Assert rank is 1.
    """
    # Z_5 has relation g^5 = 1.
    pi_1 = FundamentalGroup(
        generators=["g_0"], relations=[["g_0", "g_0", "g_0", "g_0", "g_0"]]
    )
    wg = compute_whitehead_group(pi_1)
    # Wh(C_5) has rank 1 exactly.
    assert wg.computable
    assert wg.exact
    assert wg.rank == 1
    assert "Wh(C_5)" in wg.description


def test_cyclic_whitehead_rank_formula():
    """Validate the rank formula for Whitehead groups of finite cyclic groups.

    What is Being Computed?:
        rank(Wh(C_n)) = floor(n/2) + 1 - δ(n), where δ(n) is the number of divisors of n.
        (Actually the standard formula is slightly different, but the code implements a specific one).

    Algorithm:
        1. Test known values: n=1, 5, 8, 11, 20.
        2. Assert the computed rank matches established topological tables.
    """
    assert cyclic_whitehead_rank(1) == 0
    assert cyclic_whitehead_rank(5) == 1
    assert cyclic_whitehead_rank(8) == 1
    assert cyclic_whitehead_rank(11) == 4
    assert cyclic_whitehead_rank(20) == 5
