# ─────────────────────────────────────────────────────────────────────────────
# Topological invariants of a complex, exactly (ported from TabularTopology).
#
# Included into `module SurgeryBackend`. Every kernel here is exact: integer
# arithmetic for homology / orientation / Morse / finite spaces, and certified
# floating-point predicates (with explicit refusal) for the geometric ones.
# Conventions shared with the Python side:
#   * simplices arrive as FLAT vertex arrays plus offsets (zero-copy from numpy);
#   * a simplex is oriented by its sorted vertex order, and
#     ∂[v0..vd] = Σ (-1)^i [v0..v̂i..vd];
#   * every index handed back to Python is zero-based.
# ─────────────────────────────────────────────────────────────────────────────

export classify_simplex_links_jl

"""
    _flat_simplices(flat, offsets) -> Vector{Vector{Int64}}

Unpack flat simplex storage into sorted vertex vectors.
"""
function _flat_simplices(flat::AbstractVector{Int64}, offsets::AbstractVector{Int64})
    n = length(offsets) - 1
    out = Vector{Vector{Int64}}(undef, n)
    @inbounds for i in 1:n
        out[i] = sort!(Int64[flat[j] for j in (offsets[i] + 1):offsets[i + 1]])
    end
    return out
end

"""
    _maximal_simplices(simplices) -> Vector{Vector{Int64}}

The simplices that are a proper face of no other simplex of the list.
"""
function _maximal_simplices(simplices::Vector{Vector{Int64}})
    non_max = Set{Vector{Int64}}()
    for s in simplices
        length(s) <= 1 && continue
        for i in eachindex(s)
            push!(non_max, deleteat!(copy(s), i))
        end
    end
    return [s for s in unique(simplices) if !(s in non_max)]
end

"""
    _reduced_homology_of_generators(gens) -> (Dict{Int,Tuple{Int,Vector{Int64}}}, Int)

Reduced integer homology of the complex generated by `gens`, INCLUDING degree -1:
the empty complex has H̃_{-1} = Z. Ranks and torsion come from the exact sparse SNF
(`exact_snf_sparse`: leaf-peeling + AbstractAlgebra), never from floating point.
Returns the nonzero groups and the dimension of the complex (-1 if empty).
"""
function _reduced_homology_of_generators(gens::Vector{Vector{Int64}})
    isempty(gens) && return (Dict{Int, Tuple{Int, Vector{Int64}}}(-1 => (1, Int64[])), -1)
    top = maximum(length.(gens)) - 1
    faces = [Set{Vector{Int64}}() for _ in 0:top]
    for g in gens
        for r in 1:length(g)
            for c in combinations(g, r)
                push!(faces[r], c)
            end
        end
    end
    lists = [sort!(collect(f)) for f in faces]
    idx = [Dict{Vector{Int64}, Int64}(s => Int64(i - 1) for (i, s) in enumerate(l)) for l in lists]
    ranks = zeros(Int, top + 2)            # ranks[d+1] = rank ∂_d
    tors = [Int64[] for _ in 0:top]        # tors[d+1]  = torsion of H_d
    for d in 1:top
        rows = Int64[]; cols = Int64[]; vals = Int64[]
        for (j, s) in enumerate(lists[d + 1])
            for i in 1:length(s)
                f = vcat(s[1:(i - 1)], s[(i + 1):end])
                push!(rows, idx[d][f]); push!(cols, Int64(j - 1)); push!(vals, isodd(i - 1) ? -1 : 1)
            end
        end
        factors = exact_snf_sparse(rows, cols, vals, length(lists[d]), length(lists[d + 1]))
        nz = Int64[abs(f) for f in factors if f != 0]
        ranks[d + 1] = length(nz)
        tors[d] = sort!(Int64[f for f in nz if f > 1])
    end
    red = Dict{Int, Tuple{Int, Vector{Int64}}}()
    for d in 0:top
        beta = length(lists[d + 1]) - ranks[d + 1] - ranks[d + 2]
        d == 0 && (beta -= 1)
        t = tors[d + 1]
        if beta != 0 || !isempty(t)
            red[d] = (beta, t)
        end
    end
    return red, top
end

"""
    classify_simplex_links_jl(flat, offsets, target_flat, target_offsets)

For every target simplex σ of the (face-closed) complex K given by flat storage,
compute lk(σ) -- generated by τ∖σ over the maximal τ ⊇ σ -- and return, per target,
its dimension, its purity, and its exact reduced integer homology (degree -1
included for the empty link). Targets are processed in parallel threads.

Returns `(link_dim, link_pure, hom_ptr, hom_deg, hom_rank, tor_ptr, tor_vals)`:
target t owns homology entries `hom_ptr[t]+1 : hom_ptr[t+1]`, and entry e owns
torsion coefficients `tor_ptr[e]+1 : tor_ptr[e+1]`.
"""
function classify_simplex_links_jl(flat::AbstractVector{Int64}, offsets::AbstractVector{Int64},
                                   target_flat::AbstractVector{Int64}, target_offsets::AbstractVector{Int64})
    simplices = _flat_simplices(flat, offsets)
    maximal = _maximal_simplices(simplices)
    by_vertex = Dict{Int64, Vector{Int}}()
    for (k, s) in enumerate(maximal), v in s
        push!(get!(by_vertex, v, Int[]), k)
    end
    targets = _flat_simplices(target_flat, target_offsets)
    nt = length(targets)
    link_dim = zeros(Int64, nt)
    # Vector{Bool}, NOT a BitVector: a BitVector packs 64 flags per word, so
    # concurrent writes from different threads would race on shared words.
    link_pure = zeros(Bool, nt)
    homs = Vector{Dict{Int, Tuple{Int, Vector{Int64}}}}(undef, nt)
    Threads.@threads for t in 1:nt
        σ = targets[t]
        gens = Vector{Vector{Int64}}()
        for k in get(by_vertex, σ[1], Int[])
            τ = maximal[k]
            if issubset(σ, τ)
                rest = setdiff(τ, σ)
                isempty(rest) || push!(gens, rest)
            end
        end
        red, ldim = _reduced_homology_of_generators(gens)
        homs[t] = red
        link_dim[t] = ldim
        link_pure[t] = all(g -> length(g) - 1 == ldim, gens)
    end
    hom_ptr = zeros(Int64, nt + 1)
    hom_deg = Int64[]; hom_rank = Int64[]
    tor_ptr = Int64[0]; tor_vals = Int64[]
    for t in 1:nt
        for d in sort!(collect(keys(homs[t])))
            r, tv = homs[t][d]
            push!(hom_deg, d); push!(hom_rank, r)
            append!(tor_vals, tv); push!(tor_ptr, length(tor_vals))
        end
        hom_ptr[t + 1] = length(hom_deg)
    end
    return link_dim, link_pure, hom_ptr, hom_deg, hom_rank, tor_ptr, tor_vals
end

# ── Fundamental cycles: coherent orientation over the dual graph ─────────────

export coherent_orientation_jl

"""
    coherent_orientation_jl(top_flat, top_offsets)

Coherent-sign propagation over the dual graph of a closed p-pseudomanifold whose
p-simplices are given by flat storage (hypotheses -- non-branching, no boundary,
nothing above dimension p -- are checked on the Python side). Returns
`(signs, component, orientable)`: one ±1 and one zero-based component index per
simplex, and one Bool per strong component. Signs satisfy
s_σ[σ:f] + s_τ[τ:f] = 0 across every shared facet f of an orientable component,
where [σ:f] = (-1)^j when f omits the j-th (zero-based) sorted vertex of σ.
"""
function coherent_orientation_jl(top_flat::AbstractVector{Int64}, top_offsets::AbstractVector{Int64})
    top = _flat_simplices(top_flat, top_offsets)
    n = length(top)
    owners = Dict{Vector{Int64}, Vector{Int}}()
    for (i, s) in enumerate(top), j in eachindex(s)
        push!(get!(owners, deleteat!(copy(s), j), Int[]), i)
    end
    signs = zeros(Int64, n)
    comp = fill(Int64(-1), n)
    orientable = Bool[]
    queue = Int[]
    for seed in 1:n
        signs[seed] != 0 && continue
        cid = Int64(length(orientable))
        signs[seed] = 1; comp[seed] = cid
        empty!(queue); push!(queue, seed)
        ok = true
        head = 1
        while head <= length(queue)
            i = queue[head]; head += 1
            s = top[i]
            for j in eachindex(s)
                f = deleteat!(copy(s), j)
                inc_s = isodd(j - 1) ? -1 : 1
                for nb in owners[f]
                    nb == i && continue
                    t = top[nb]
                    jn = findfirst(v -> !(v in f), t)
                    inc_t = isodd(jn - 1) ? -1 : 1
                    want = -signs[i] * inc_s * inc_t
                    if signs[nb] == 0
                        signs[nb] = want; comp[nb] = cid
                        push!(queue, nb)
                    elseif signs[nb] != want
                        ok = false
                    end
                end
            end
        end
        push!(orientable, ok)
    end
    return signs, comp, orientable
end

# ── Finite spaces: Stong cores; simplicial strong collapses ──────────────────

export stong_core_jl, strong_collapse_jl

"""
    stong_core_jl(down_flat, down_offsets)

Stong core of a finite T0 space given by the down-set U(x) of every point x
(zero-based, flat storage). Beat points -- U(x)∖{x} with a maximum, or F(x)∖{x}
with a minimum -- are removed by a worklist in which only the neighbours of a
removed point are re-queued (sorted, and the smallest admissible target is taken,
so the result matches the Python backend point for point).

Returns `(alive, redirect_from, redirect_to)`, all zero-based: the surviving points
and, for every removed point, the point it retracted onto.
"""
function stong_core_jl(down_flat::AbstractVector{Int64}, down_offsets::AbstractVector{Int64})
    n = length(down_offsets) - 1
    down = [Set{Int}(Int(down_flat[j]) + 1 for j in (down_offsets[i] + 1):down_offsets[i + 1]) for i in 1:n]
    up = [Set{Int}() for _ in 1:n]
    for x in 1:n, y in down[x]
        push!(up[y], x)
    end
    alive = trues(n); n_alive = n
    redirect_from = Int64[]; redirect_to = Int64[]
    queue = collect(1:n); queued = trues(n); head = 1
    while head <= length(queue) && n_alive > 1
        x = queue[head]; head += 1
        queued[x] = false
        alive[x] || continue
        t = 0
        uh = setdiff(down[x], x)
        for m in sort!(collect(uh))
            if issubset(uh, down[m]); t = m; break; end
        end
        if t == 0
            fh = setdiff(up[x], x)
            for m in sort!(collect(fh))
                if issubset(fh, up[m]); t = m; break; end
            end
        end
        t == 0 && continue
        push!(redirect_from, x - 1); push!(redirect_to, t - 1)
        neighbours = setdiff(union(down[x], up[x]), x)
        for y in up[x]; y == x || delete!(down[y], x); end
        for y in down[x]; y == x || delete!(up[y], x); end
        alive[x] = false; n_alive -= 1
        empty!(down[x]); empty!(up[x])
        for y in sort!(collect(neighbours))
            if alive[y] && !queued[y]
                push!(queue, y); queued[y] = true
            end
        end
    end
    return Int64[i - 1 for i in 1:n if alive[i]], redirect_from, redirect_to
end

"""
    strong_collapse_jl(max_flat, max_offsets)

Strong collapse (Barmak-Minian) of the complex whose MAXIMAL simplices are given in
flat storage: repeatedly delete a vertex v dominated by some v' ≠ v (every maximal
simplex through v contains v'; the smallest such v' is recorded). Deleting v
replaces each facet σ ∋ v by σ∖v, kept only if it is not contained in a facet
through v'. Returns `(core_flat, core_offsets, removed_v, removed_by)`.
"""
function strong_collapse_jl(max_flat::AbstractVector{Int64}, max_offsets::AbstractVector{Int64})
    maximal = _flat_simplices(max_flat, max_offsets)
    facets = Dict{Int, Set{Int64}}(i => Set{Int64}(s) for (i, s) in enumerate(maximal))
    star = Dict{Int64, Set{Int}}()
    for (i, s) in facets, v in s
        push!(get!(star, v, Set{Int}()), i)
    end
    removed_v = Int64[]; removed_by = Int64[]
    queue = sort!(collect(keys(star))); queued = Set{Int64}(queue); head = 1
    while head <= length(queue) && length(star) > 1
        v = queue[head]; head += 1
        delete!(queued, v)
        haskey(star, v) || continue
        common = nothing
        dominated = true
        for i in star[v]
            common = common === nothing ? copy(facets[i]) : intersect!(common, facets[i])
            if length(common) <= 1; dominated = false; break; end
        end
        dominated || continue
        delete!(common, v)
        isempty(common) && continue
        w = minimum(common)
        push!(removed_v, v); push!(removed_by, w)
        touched = Set{Int64}()
        for i in collect(star[v])
            new = setdiff(facets[i], (v,))
            union!(touched, new)
            delete!(facets, i)
            for u in new; delete!(star[u], i); end
            if !isempty(new) && !any(j -> issubset(new, facets[j]) && new != facets[j], star[w]) &&
               !any(j -> new == facets[j], star[w])
                facets[i] = new
                for u in new; push!(star[u], i); end
            end
        end
        delete!(star, v)
        for u in sort!(collect(touched))
            if haskey(star, u) && !(u in queued)
                push!(queue, u); push!(queued, u)
            end
        end
    end
    core = sort!([sort!(collect(f)) for f in values(facets)], by = s -> (length(s), s))
    core_flat = Int64[v for s in core for v in s]
    core_offsets = zeros(Int64, length(core) + 1)
    for (k, s) in enumerate(core); core_offsets[k + 1] = core_offsets[k] + length(s); end
    return core_flat, core_offsets, removed_v, removed_by
end

# ── Lower-star discrete Morse theory and Z/2 persistence pairs ───────────────

export lower_star_gradient_jl, z2_persistence_pairs_jl

# The RWS priority of a cell of the lower star of v: the (value, label) keys of its
# OTHER vertices, sorted descending, compared lexicographically (as Python tuples).
function _rws_key(s::Vector{Int64}, v::Int64, key::Dict{Int64, Tuple{Float64, Int64}})
    return sort!([key[u] for u in s if u != v]; rev = true)
end

# Pop the cell with the smallest key that is not yet assigned (linear scan: lower
# stars are small, and it reproduces the Python heap order exactly -- keys of
# distinct cells never tie).
function _rws_pop!(pq::Vector{Tuple{Vector{Tuple{Float64, Int64}}, Int}}, assigned::Set{Int})
    while !isempty(pq)
        k = argmin(first.(pq))
        _, c = pq[k]
        deleteat!(pq, k)
        c in assigned || return c
    end
    return 0
end

"""
    lower_star_gradient_jl(flat, offsets, vert_ids, vert_vals)

Robins-Wood-Sheppard lower-star discrete gradient. `flat/offsets` hold every
simplex of K in canonical (dimension, vertices) order; `vert_ids/vert_vals` the
vertex function. Lower stars are processed in parallel threads (pairings never
leave a lower star). Returns zero-based cell indices
`(pair_low, pair_high, critical)`, listed vertex by vertex in increasing label order
-- identical to the Python backend.
"""
function lower_star_gradient_jl(flat::AbstractVector{Int64}, offsets::AbstractVector{Int64},
                                vert_ids::AbstractVector{Int64}, vert_vals::AbstractVector{Float64})
    cells = _flat_simplices(flat, offsets)
    index = Dict{Vector{Int64}, Int}(s => i for (i, s) in enumerate(cells))
    key = Dict{Int64, Tuple{Float64, Int64}}(Int64(v) => (Float64(x), Int64(v)) for (v, x) in zip(vert_ids, vert_vals))
    verts = sort!(collect(Int64, vert_ids))
    vpos = Dict{Int64, Int}(v => i for (i, v) in enumerate(verts))
    lower = [Int[] for _ in verts]
    for (i, s) in enumerate(cells)
        top = s[argmax([key[u] for u in s])]
        push!(lower[vpos[top]], i)
    end
    res_low = [Int[] for _ in verts]; res_high = [Int[] for _ in verts]; res_crit = [Int[] for _ in verts]
    Threads.@threads for vi in eachindex(verts)
        v = verts[vi]
        L = lower[vi]
        vcell = index[[v]]
        if length(L) == 1
            push!(res_crit[vi], vcell)
            continue
        end
        Lset = Set{Int}(L)
        assigned = Set{Int}()
        cofacets = Dict{Int, Vector{Int}}(c => Int[] for c in L)
        for c in L
            s = cells[c]
            length(s) <= 1 && continue
            for j in eachindex(s)
                f = get(index, deleteat!(copy(s), j), 0)
                (f != 0 && f in Lset) && push!(cofacets[f], c)
            end
        end
        unpaired(c) = begin
            s = cells[c]; out = Int[]
            if length(s) > 1
                for j in eachindex(s)
                    f = index[deleteat!(copy(s), j)]
                    (f in Lset && !(f in assigned)) && push!(out, f)
                end
            end
            out
        end
        edges = [c for c in L if length(cells[c]) == 2]
        delta = edges[argmin([_rws_key(cells[c], v, key) for c in edges])]
        push!(res_low[vi], vcell); push!(res_high[vi], delta)
        push!(assigned, vcell); push!(assigned, delta)
        pq_zero = Tuple{Vector{Tuple{Float64, Int64}}, Int}[]
        pq_one = Tuple{Vector{Tuple{Float64, Int64}}, Int}[]
        for c in edges
            c == delta || push!(pq_zero, (_rws_key(cells[c], v, key), c))
        end
        for c in cofacets[delta]
            length(unpaired(c)) == 1 && push!(pq_one, (_rws_key(cells[c], v, key), c))
        end
        push_cofacets(c) = for b in cofacets[c]
            if !(b in assigned) && length(unpaired(b)) == 1
                push!(pq_one, (_rws_key(cells[b], v, key), b))
            end
        end
        while true
            alpha = _rws_pop!(pq_one, assigned)
            if alpha != 0
                free = unpaired(alpha)
                if isempty(free)
                    push!(pq_zero, (_rws_key(cells[alpha], v, key), alpha))
                else
                    facet = free[1]
                    push!(res_low[vi], facet); push!(res_high[vi], alpha)
                    push!(assigned, facet); push!(assigned, alpha)
                    push_cofacets(alpha); push_cofacets(facet)
                end
                continue
            end
            gamma = _rws_pop!(pq_zero, assigned)
            gamma == 0 && break
            push!(res_crit[vi], gamma); push!(assigned, gamma)
            push_cofacets(gamma)
        end
    end
    return (Int64[c - 1 for r in res_low for c in r], Int64[c - 1 for r in res_high for c in r],
            Int64[c - 1 for r in res_crit for c in r])
end

"""
    z2_persistence_pairs_jl(flat, offsets)

Standard Z/2 column reduction of a filtration whose simplices are given IN
FILTRATION ORDER (faces before cofaces). Returns zero-based `(birth, death)`
positions sorted by birth; `death == -1` marks an essential class.
"""
function z2_persistence_pairs_jl(flat::AbstractVector{Int64}, offsets::AbstractVector{Int64})
    cells = _flat_simplices(flat, offsets)
    position = Dict{Vector{Int64}, Int}(s => i for (i, s) in enumerate(cells))
    n = length(cells)
    columns = Vector{Vector{Int}}(undef, n)
    low_to_col = zeros(Int, n)
    col = Int[]; scratch = Int[]
    for j in 1:n
        s = cells[j]
        col = length(s) > 1 ? sort!([position[deleteat!(copy(s), i)] for i in eachindex(s)]) : Int[]
        while !isempty(col)
            owner = low_to_col[col[end]]
            owner == 0 && break
            _symdiff_into!(scratch, col, columns[owner])
            col, scratch = scratch, col
        end
        isempty(col) || (low_to_col[col[end]] = j)
        columns[j] = copy(col)
    end
    births = Int64[]; deaths = Int64[]
    dead = falses(n)
    for b in 1:n
        if low_to_col[b] != 0
            dead[b] = true; dead[low_to_col[b]] = true
        end
    end
    for i in 1:n
        if low_to_col[i] != 0
            push!(births, i - 1); push!(deaths, low_to_col[i] - 1)
        elseif !dead[i]
            push!(births, i - 1); push!(deaths, -1)
        end
    end
    return births, deaths
end

# ── Geometric linking: certified rays and cone apices ───────────────────────

export winding_numbers_jl, cone_intersection_count_jl

"""
    winding_numbers_jl(points, simp, coef, coords, directions, tol)

Winding number of every point (rows of `points`) with respect to the simplicial
(m-1)-cycle `simp` (rows = zero-based vertex indices, orientation = listed order)
with coefficients `coef`, by ONE certified generic ray per point, the first of the
fixed `directions` (rows) that passes the genericity test. Points run in parallel
threads. Returns `(values, status)` per point: status 0 ok, 1 the point lies on the
cycle (undefined), 2 no generic ray. Mirrors the Python reference step for step.
"""
function winding_numbers_jl(points::AbstractMatrix{Float64}, simp::AbstractMatrix{Int64},
                            coef::AbstractVector{Int64}, coords::AbstractMatrix{Float64},
                            directions::AbstractMatrix{Float64}, tol::Float64)
    npts, m = size(points)
    ns = size(simp, 1)
    V = [Matrix{Float64}(coords[simp[k, :] .+ 1, :]) for k in 1:ns]          # rows = vertices
    E = [V[k][2:end, :] .- V[k][1:1, :] for k in 1:ns]                        # (m-1) x m
    values = zeros(Int64, npts); status = zeros(Int64, npts)
    Threads.@threads for i in 1:npts
        x = Vector{Float64}(points[i, :])
        scale = maximum(abs.(coords .- x'))
        scale == 0.0 && (scale = 1.0)
        st = 2; val = 0
        for r in 1:size(directions, 1)
            d = Vector{Float64}(directions[r, :])
            okdir = true; ongrid = false; graze = false
            acc = 0
            for k in 1:ns
                M = hcat(d, -transpose(E[k]))                                   # columns
                dt = det(M)
                nrm = prod(sqrt(sum(abs2, M[:, j])) for j in 1:m)
                if !(abs(dt) > 1e-12 * max(nrm, 1e-300))
                    nvec = svd(E[k]; full = true).V[:, end]
                    if abs(dot(nvec, x .- V[k][1, :])) <= tol * scale
                        okdir = false; break
                    end
                    continue
                end
                sol = M \ (V[k][1, :] .- x)
                t = sol[1]; lam = sol[2:end]
                bary = vcat(1 - sum(lam), lam)
                if all(bary .> -tol)
                    if abs(t) <= tol * scale
                        ongrid = true; break
                    end
                    if t > 0
                        if any(bary .< tol)
                            graze = true
                        else
                            acc += coef[k] * Int(sign(det(vcat(transpose(d), E[k]))))
                        end
                    end
                end
            end
            if ongrid
                st = 1; break
            end
            (okdir && !graze) || continue
            st = 0; val = acc
            break
        end
        values[i] = val; status[i] = st
    end
    return values, status
end

"""
    cone_intersection_count_jl(VA, cA, VB, cB, o, tol, scale)

Intersection number of the cone o*A (A a simplicial p-cycle, B a q-cycle,
p + q = m - 1) with B. `VA` is (nA, p+1, m), `VB` is (nB, q+1, m) -- the vertex
coordinates of each simplex. Pairs whose bounding boxes meet are solved; the apex is
certified only if every intersection is interior by the relative margin `tol` and
every singular pair is parallel and apart. Cone simplices run in parallel threads.
Returns `(total, status)`: status 0 ok, 1 degenerate apex (try the next), 2 B passes
through A (linking undefined).
"""
function cone_intersection_count_jl(VA::AbstractArray{Float64, 3}, cA::AbstractVector{Int64},
                                    VB::AbstractArray{Float64, 3}, cB::AbstractVector{Int64},
                                    o::AbstractVector{Float64}, tol::Float64, scale::Float64)
    nA, p1, m = size(VA); nB, q1, _ = size(VB)
    loB = [vec(minimum(VB[b, :, :]; dims = 1)) for b in 1:nB]
    hiB = [vec(maximum(VB[b, :, :]; dims = 1)) for b in 1:nB]
    EB = [VB[b, 2:end, :] .- VB[b, 1:1, :] for b in 1:nB]                      # q x m
    part = zeros(Int64, nA); through = zeros(Bool, nA); degen = zeros(Bool, nA)
    Threads.@threads for a in 1:nA
        EA = VA[a, :, :] .- transpose(o)                                        # (p+1) x m
        loA = min.(vec(minimum(VA[a, :, :]; dims = 1)), o)
        hiA = max.(vec(maximum(VA[a, :, :]; dims = 1)), o)
        for b in 1:nB
            all(loA .<= hiB[b] .+ tol * scale) && all(hiA .>= loB[b] .- tol * scale) || continue
            F = vcat(EA, EB[b])                                                  # rows = frame
            dt = det(F)
            nrm = prod(sqrt(sum(abs2, F[j, :])) for j in 1:m)
            M = transpose(vcat(EA, -EB[b]))                                      # columns
            rhs = VB[b, 1, :] .- o
            if abs(dt) > 1e-12 * max(nrm, 1e-300)
                sol = M \ rhs
                lam = sol[1:p1]; mu = sol[(p1 + 1):end]
                bl = vcat(1 - sum(lam), lam); bm = vcat(1 - sum(mu), mu)
                if all(bl .> -tol) && all(bm .> -tol)
                    bl[1] < tol && (through[a] = true)
                    (any(bl .< tol) || any(bm .< tol)) && (degen[a] = true)
                    part[a] += cA[a] * cB[b] * Int(sign(dt))
                end
            else
                F2 = svd(Matrix(M))
                null = F2.S .<= 1e-9 * max(F2.S[1], 1e-300)
                comp = transpose(F2.U) * rhs
                gap = sqrt(sum(abs2, comp[null]))
                gap <= 1e-6 * scale && (degen[a] = true)
            end
        end
    end
    any(through) && return (Int64(0), Int64(2))
    any(degen) && return (Int64(0), Int64(1))
    return (Int64(sum(part)), Int64(0))
end

# ── Knot diagrams and homomorphism counts ────────────────────────────────────

export diagram_crossings_jl, count_homomorphisms_jl

_cross2d(a1, a2, b1, b2) = a1 * b2 - a2 * b1

"""
    diagram_crossings_jl(S, E, comp, loc, ncomp, e1, e2, u, tol, scale)

Crossings of the closed polygons with segments `S[k,:] -> E[k,:]` (component
`comp[k]`, local index `loc[k]`, component length `ncomp[k]`) in the projection frame
(e1, e2, u). Every non-adjacent pair is tested (rows in parallel threads) for
collinear overlap, a crossing at an endpoint, and depth separation. Returns
`(a, b, t, w, da, db, status, meet_a, meet_b, meet_gap)`: the raw crossings (zero-based
segment indices, parameters along each, depths), status 0 generic / 1 collinear
overlap / 2 endpoint crossing / 3 the polygons (nearly) meet, and the closest meeting
pair. Mirrors the Python reference.
"""
function diagram_crossings_jl(S::AbstractMatrix{Float64}, E::AbstractMatrix{Float64},
                              comp::AbstractVector{Int64}, loc::AbstractVector{Int64}, ncomp::AbstractVector{Int64},
                              e1::AbstractVector{Float64}, e2::AbstractVector{Float64}, u::AbstractVector{Float64},
                              tol::Float64, scale::Float64)
    N = size(S, 1)
    Sm = Matrix{Float64}(S); Em = Matrix{Float64}(E)
    P1x = Sm * e1; P1y = Sm * e2
    Rx = Em * e1 .- P1x; Ry = Em * e2 .- P1y
    D1 = Sm * u; D2 = Em * u
    rnorm = sqrt.(Rx .^ 2 .+ Ry .^ 2)
    rows = [Tuple{Int, Int, Float64, Float64, Float64, Float64}[] for _ in 1:N]
    collinear = zeros(Bool, N); endpoint = zeros(Bool, N)
    meet_gap = fill(Inf, N); meet_b = zeros(Int, N)
    Threads.@threads for i in 1:N
        for j in (i + 1):N
            if comp[i] == comp[j]
                dl = abs(loc[i] - loc[j])
                (dl == 1 || dl == ncomp[i] - 1) && continue
            end
            rx, ry, sx, sy = Rx[i], Ry[i], Rx[j], Ry[j]
            qx, qy = P1x[j] - P1x[i], P1y[j] - P1y[i]
            rxs = _cross2d(rx, ry, sx, sy)
            if abs(rxs) <= 1e-12 * rnorm[i] * rnorm[j]
                off = abs(_cross2d(qx, qy, rx, ry)) / max(rnorm[i], 1e-300)
                if off <= tol * scale
                    rr = rx * rx + ry * ry
                    a0 = (qx * rx + qy * ry) / rr
                    a1 = ((qx + sx) * rx + (qy + sy) * ry) / rr
                    if max(a0, a1) >= -tol && min(a0, a1) <= 1 + tol
                        collinear[i] = true
                    end
                end
                continue
            end
            t = _cross2d(qx, qy, sx, sy) / rxs
            w = _cross2d(qx, qy, rx, ry) / rxs
            (t > -tol && t < 1 + tol && w > -tol && w < 1 + tol) || continue
            if t < tol || t > 1 - tol || w < tol || w > 1 - tol
                endpoint[i] = true
                continue
            end
            da = D1[i] + t * (D2[i] - D1[i]); db = D1[j] + w * (D2[j] - D1[j])
            gap = abs(da - db)
            if gap <= tol * scale && gap < meet_gap[i]
                meet_gap[i] = gap; meet_b[i] = j
            end
            push!(rows[i], (i, j, t, w, da, db))
        end
    end
    status = any(collinear) ? 1 : any(endpoint) ? 2 : any(isfinite, meet_gap) ? 3 : 0
    k = argmin(meet_gap)
    flat = [r for rs in rows for r in rs]
    return (Int64[r[1] - 1 for r in flat], Int64[r[2] - 1 for r in flat],
            Float64[r[3] for r in flat], Float64[r[4] for r in flat],
            Float64[r[5] for r in flat], Float64[r[6] for r in flat],
            Int64(status), Int64(k - 1), Int64(meet_b[k] - 1), Float64(meet_gap[k]))
end

function _lex_permutations(n::Int)
    out = Vector{Vector{Int}}()
    rec(prefix, rest) = if isempty(rest)
        push!(out, copy(prefix))
    else
        for (k, x) in enumerate(rest)
            push!(prefix, x); rec(prefix, [rest[1:(k - 1)]; rest[(k + 1):end]]); pop!(prefix)
        end
    end
    rec(Int[], collect(0:(n - 1)))
    return out
end

"""
    count_homomorphisms_jl(n, constrained, rel_gens, rel_exps, rel_offsets, at_flat, at_offsets, budget)

|Hom(G, S_n)| restricted to the generators that occur in relators, by backtracking in
exactly the order the Python side prescribes: `constrained` lists the generators
(zero-based) in assignment order, relator r is `rel_gens/rel_exps[rel_offsets[r]+1 :
rel_offsets[r+1]]`, and the relators checked after assigning position i are
`at_flat[at_offsets[i]+1 : at_offsets[i+1]]`. Permutations are tried in
lexicographic order (as `itertools.permutations`). `budget < 0` means no budget.
Returns `(count_string, exact, tried)`; the count is returned as a decimal string
(Int128 internally) so no precision is lost crossing to Python.
"""
function count_homomorphisms_jl(n::Int, constrained::AbstractVector{Int64},
                                rel_gens::AbstractVector{Int64}, rel_exps::AbstractVector{Int64},
                                rel_offsets::AbstractVector{Int64}, at_flat::AbstractVector{Int64},
                                at_offsets::AbstractVector{Int64}, budget::Int)
    perms = _lex_permutations(n)
    inv = [invperm(p .+ 1) .- 1 for p in perms]
    nrel = length(rel_offsets) - 1
    words = [[(Int(rel_gens[t]), Int(rel_exps[t])) for t in (rel_offsets[r] + 1):rel_offsets[r + 1]] for r in 1:nrel]
    L = length(constrained)
    checks = [[Int(at_flat[t]) + 1 for t in (at_offsets[i] + 1):at_offsets[i + 1]] for i in 1:L]
    assign = zeros(Int, maximum(constrained; init = 0) + 1)   # generator -> perm index
    count = Ref(Int128(0)); tried = Ref(0); exact = Ref(true)
    cur = zeros(Int, n); tmp = zeros(Int, n)
    function holds(r)
        for i in 1:n; cur[i] = i - 1; end
        for (g, e) in words[r]
            q = e > 0 ? perms[assign[g + 1]] : inv[assign[g + 1]]
            for i in 1:n; tmp[i] = cur[q[i] + 1]; end
            copyto!(cur, tmp)
        end
        for i in 1:n
            cur[i] == i - 1 || return false
        end
        return true
    end
    function rec(i)
        exact[] || return
        if i > L
            count[] += 1
            return
        end
        g = Int(constrained[i])
        for p in eachindex(perms)
            tried[] += 1
            if budget >= 0 && tried[] > budget
                exact[] = false
                return
            end
            assign[g + 1] = p
            ok = true
            for r in checks[i]
                if !holds(r); ok = false; break; end
            end
            ok && rec(i + 1)
            exact[] || return
        end
    end
    rec(1)
    return string(count[]), exact[], Int64(tried[])
end

# ── Holonomy transports and the Federer reach ────────────────────────────────

export edge_transport_data_jl, federer_reach_jl

"""
    edge_transport_data_jl(F, pairs)

For every directed pair (i, j) (rows of `pairs`, zero-based) of local-PCA frames
`F` (n × ambient × d): the sign of det(F_jᵀ F_i) -- the orientation character of the
discrete Levi-Civita transport -- and the smallest singular value of F_jᵀ F_i (the
cosine of the largest principal angle, which decides whether that sign is reliable).
Pairs run in parallel threads.
"""
function edge_transport_data_jl(F::AbstractArray{Float64, 3}, pairs::AbstractMatrix{Int64})
    m = size(pairs, 1)
    sg = zeros(Int64, m); mincos = zeros(Float64, m)
    Threads.@threads for t in 1:m
        i = pairs[t, 1] + 1; j = pairs[t, 2] + 1
        M = transpose(F[j, :, :]) * F[i, :, :]
        sg[t] = Int64(sign(det(M)))
        mincos[t] = minimum(svdvals(M))
    end
    return sg, mincos
end

"""
    federer_reach_jl(X, P)

Federer's reach estimate inf_{x≠y} |y-x|² / (2 d(y-x, T_x)) over ALL ordered pairs of
the sample X (n × ambient), with T_x spanned by the orthonormal columns of P[x,:,:]
(n × ambient × d). Pairs with y - x in T_x contribute nothing. Points run in parallel
threads; returns Inf when no pair constrains the reach (a flat sample).
"""
function federer_reach_jl(X::AbstractMatrix{Float64}, P::AbstractArray{Float64, 3})
    n = size(X, 1)
    Xm = Matrix{Float64}(X)
    best = fill(Inf, n)
    Threads.@threads for i in 1:n
        Pi = Matrix{Float64}(P[i, :, :])
        xi = Xm[i, :]
        b = Inf
        for j in 1:n
            j == i && continue
            v = Xm[j, :] .- xi
            n2 = sum(abs2, v)
            n2 == 0.0 && continue
            perp = sqrt(sum(abs2, v .- Pi * (transpose(Pi) * v)))
            perp == 0.0 && continue
            c = n2 / (2 * perp)
            isfinite(c) && c < b && (b = c)
        end
        best[i] = b
    end
    return minimum(best)
end

# ── Precompilation of the kernels above (cached in the package image) ────────

PrecompileTools.@setup_workload begin
  let
    tri_flat = Int64[0, 1, 2, 0, 1, 0, 2, 1, 2, 0, 1, 2]
    tri_off = Int64[0, 1, 2, 3, 5, 7, 9, 12]
    tet_flat = Int64[0, 1, 2, 0, 1, 3, 0, 2, 3, 1, 2, 3]
    tet_off = Int64[0, 3, 6, 9, 12]
    PrecompileTools.@compile_workload begin
        classify_simplex_links_jl(tri_flat, tri_off, tri_flat, tri_off)
        coherent_orientation_jl(tet_flat, tet_off)
        stong_core_jl(Int64[0, 1, 0, 1, 2], Int64[0, 1, 2, 5])
        strong_collapse_jl(Int64[0, 1, 2], Int64[0, 3])
        lower_star_gradient_jl(tri_flat, tri_off, Int64[0, 1, 2], Float64[0.0, 1.0, 2.0])
        z2_persistence_pairs_jl(tri_flat, tri_off)
        count_homomorphisms_jl(3, Int64[0], Int64[0, 0], Int64[1, 1], Int64[0, 2], Int64[0], Int64[0, 1], -1)
    end
  end
end
