"""Known homotopy groups: verification ground truth.

WARNING: This module exists for verification only. The public homotopy
pipeline (``compute_pi_n``) must NEVER import this module to construct
output; it is consulted only by ``homotopy_verifier.verify_against_known``
to compare a computed value against a published one.

Entries are encoded as ``(free_rank, torsion_invariant_factors,
p_primary_summary, source, confidence)``.

References:
    Toda, H. (1962). Composition Methods in the Homotopy Groups of Spheres.
        Princeton University Press.
    Mimura, M., Toda, H. (1969). Topology of Lie Groups, I and II.
        Translations of Mathematical Monographs 91, AMS (1991).
    James, I. M. (1955). Reduced product spaces. Ann. Math. 62, 170-197.
    McGibbon, C. A. (1980). Stable properties of rank 1 loop structures.
        Topology 19, 257-265.
    Hilton, P. J. (1955). On the homotopy groups of the union of spheres.
        J. London Math. Soc. 30, 154-172.
    Bott, R. (1959). The stable homotopy of the classical groups.
        Ann. Math. 70, 313-337.
"""
from __future__ import annotations

from typing import Dict, List, Optional, Tuple

from pydantic import BaseModel, ConfigDict, Field


# ── Schema ────────────────────────────────────────────────────────────────────


class KnownHomotopyEntry(BaseModel):
    """One row of a known homotopy table.

    Attributes:
        free_rank: dim_ℚ(π_n ⊗ ℚ).
        torsion: Invariant-factor list (e.g., ``[2, 12]`` for Z/2 ⊕ Z/12).
            Empty tuple means trivial torsion.
        p_primary: Per-prime decomposition; values are invariant factors at
            that prime. Used by the multi-prime synthesizer cross-check.
        source: Citation key for the original publication.
        confidence: One of ``"published"``, ``"derived"``, ``"conjectural"``.
            ``"published"`` means a direct lift from a peer-reviewed table.
            ``"derived"`` means it follows from a published result via a
            structural argument (Hilton splitting, suspension, Bott
            periodicity, etc.). ``"conjectural"`` means it is unproved.
    """

    model_config = ConfigDict(frozen=True)

    free_rank: int = Field(ge=0)
    torsion: Tuple[int, ...] = ()
    p_primary: Dict[int, Tuple[int, ...]] = Field(default_factory=dict)
    source: str = ""
    confidence: str = "published"

    def group_string(self) -> str:
        """Render as ``Z^r ⊕ Z/d_1 ⊕ ... ⊕ Z/d_k`` (or ``0`` if trivial)."""
        parts: List[str] = []
        if self.free_rank == 1:
            parts.append("Z")
        elif self.free_rank > 1:
            parts.append(f"Z^{self.free_rank}")
        for d in self.torsion:
            parts.append(f"Z/{d}")
        return " ⊕ ".join(parts) if parts else "0"


class KnownHomotopyTable(BaseModel):
    """A family of known homotopy groups keyed by stem n."""

    model_config = ConfigDict(frozen=True)

    family: str
    parameter: Optional[int] = None
    entries: Dict[int, KnownHomotopyEntry]
    n_min: int = 1
    n_max: int = 18
    notes: str = ""


# ── Sphere tables ─────────────────────────────────────────────────────────────
#
# π_n(S^k) for k = 1..7, with n up to the published range in Toda 1962 and
# Mimura-Toda 1969. We only include rigorously published values.


def _E(
    free_rank: int = 0,
    torsion: Tuple[int, ...] = (),
    p_primary: Optional[Dict[int, Tuple[int, ...]]] = None,
    source: str = "Toda1962",
    confidence: str = "published",
) -> KnownHomotopyEntry:
    return KnownHomotopyEntry(
        free_rank=free_rank,
        torsion=torsion,
        p_primary=p_primary or {},
        source=source,
        confidence=confidence,
    )


# π_n(S^1): contractible loop space; π_1 = Z, all higher π_n = 0.
_PI_S1: Dict[int, KnownHomotopyEntry] = {
    1: _E(free_rank=1, source="Hatcher.AT.1.1"),
    **{n: _E() for n in range(2, 19)},
}

# π_n(S^2). Well-known via the Hopf fibration η: S^3 → S^2.
# Below we lift the entries from Toda 1962 Table A.3 / Hatcher AT §4.
_PI_S2: Dict[int, KnownHomotopyEntry] = {
    1: _E(),
    2: _E(free_rank=1, source="Hopf1931"),
    3: _E(free_rank=1, source="Hopf1931"),  # generated by η
    4: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    5: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    6: _E(torsion=(12,), p_primary={2: (4,), 3: (3,)}, source="Toda1962"),
    7: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    8: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    9: _E(torsion=(3,), p_primary={3: (3,)}, source="Toda1962"),
    10: _E(torsion=(15,), p_primary={3: (3,), 5: (5,)}, source="Toda1962"),
    11: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    12: _E(torsion=(2, 2), p_primary={2: (2, 2)}, source="Toda1962"),
    13: _E(torsion=(12, 2), p_primary={2: (4, 2), 3: (3,)}, source="Toda1962"),
    14: _E(torsion=(84, 2, 2), p_primary={2: (4, 2, 2), 3: (3,), 7: (7,)}, source="Toda1962"),
}

# π_n(S^3). Same as π_n(S^2) for n ≥ 3 via the Hopf fibration long exact
# sequence (π_n(S^2) ≅ π_n(S^3) for n ≥ 3; the kernel is generated by η).
_PI_S3: Dict[int, KnownHomotopyEntry] = {
    1: _E(),
    2: _E(),
    3: _E(free_rank=1, source="Hatcher.AT.4"),
    4: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    5: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    6: _E(torsion=(12,), p_primary={2: (4,), 3: (3,)}, source="Toda1962"),
    7: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    8: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    9: _E(torsion=(3,), p_primary={3: (3,)}, source="Toda1962"),
    10: _E(torsion=(15,), p_primary={3: (3,), 5: (5,)}, source="Toda1962"),
    11: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    12: _E(torsion=(2, 2), p_primary={2: (2, 2)}, source="Toda1962"),
    13: _E(torsion=(12, 2), p_primary={2: (4, 2), 3: (3,)}, source="Toda1962"),
    14: _E(torsion=(84, 2, 2), p_primary={2: (4, 2, 2), 3: (3,), 7: (7,)}, source="Toda1962"),
}

# π_n(S^4). Has Z in π_4 and Z in π_7 (the Hopf fibration ν: S^7 → S^4).
_PI_S4: Dict[int, KnownHomotopyEntry] = {
    1: _E(),
    2: _E(),
    3: _E(),
    4: _E(free_rank=1, source="Hatcher.AT.4"),
    5: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    6: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    7: _E(free_rank=1, torsion=(12,), p_primary={2: (4,), 3: (3,)}, source="Toda1962"),
    8: _E(torsion=(2, 2), p_primary={2: (2, 2)}, source="Toda1962"),
    9: _E(torsion=(2, 2), p_primary={2: (2, 2)}, source="Toda1962"),
    10: _E(torsion=(24, 3), p_primary={2: (8,), 3: (3, 3)}, source="Toda1962"),
    11: _E(torsion=(15,), p_primary={3: (3,), 5: (5,)}, source="Toda1962"),
    12: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    13: _E(torsion=(2, 2), p_primary={2: (2, 2)}, source="Toda1962"),
    14: _E(torsion=(24, 12, 2), p_primary={2: (8, 4, 2), 3: (3, 3)}, source="Toda1962"),
}

# π_n(S^5).
_PI_S5: Dict[int, KnownHomotopyEntry] = {
    **{n: _E() for n in range(1, 5)},
    5: _E(free_rank=1, source="Hatcher.AT.4"),
    6: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    7: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    8: _E(torsion=(24,), p_primary={2: (8,), 3: (3,)}, source="Toda1962"),
    9: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    10: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    11: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    12: _E(torsion=(30,), p_primary={2: (2,), 3: (3,), 5: (5,)}, source="Toda1962"),
    13: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    14: _E(torsion=(72, 2), p_primary={2: (8, 2), 3: (9,)}, source="Toda1962"),
}

# π_n(S^6).
_PI_S6: Dict[int, KnownHomotopyEntry] = {
    **{n: _E() for n in range(1, 6)},
    6: _E(free_rank=1, source="Hatcher.AT.4"),
    7: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    8: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    9: _E(torsion=(24,), p_primary={2: (8,), 3: (3,)}, source="Toda1962"),
    10: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    11: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    12: _E(free_rank=1, torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    13: _E(torsion=(60,), p_primary={2: (4,), 3: (3,), 5: (5,)}, source="Toda1962"),
    14: _E(torsion=(24, 2), p_primary={2: (8, 2), 3: (3,)}, source="Toda1962"),
}

# π_n(S^7). Has Z in π_7 and Z in π_15 (the Hopf fibration σ: S^15 → S^8 is at
# the next sphere, but π_7(S^7) = Z; π_n(S^7) for 7 < n ≤ 14 follows Toda).
_PI_S7: Dict[int, KnownHomotopyEntry] = {
    **{n: _E() for n in range(1, 7)},
    7: _E(free_rank=1, source="Hatcher.AT.4"),
    8: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    9: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    10: _E(torsion=(24,), p_primary={2: (8,), 3: (3,)}, source="Toda1962"),
    11: _E(torsion=(2,), p_primary={2: (2,)}, source="Toda1962"),
    12: _E(torsion=(2, 2), p_primary={2: (2, 2)}, source="Toda1962"),
    13: _E(torsion=(2, 2, 2), p_primary={2: (2, 2, 2)}, source="Toda1962"),
    14: _E(torsion=(2, 2, 2), p_primary={2: (2, 2, 2)}, source="Toda1962"),
}


def _make_sphere_table(k: int, entries: Dict[int, KnownHomotopyEntry]) -> KnownHomotopyTable:
    n_max = max(entries) if entries else 18
    return KnownHomotopyTable(
        family="S",
        parameter=k,
        entries=entries,
        n_min=1,
        n_max=n_max,
        notes="Toda 1962 / Mimura-Toda 1969; see source field per entry.",
    )


KNOWN_PI_N_SPHERES: Dict[int, KnownHomotopyTable] = {
    1: _make_sphere_table(1, _PI_S1),
    2: _make_sphere_table(2, _PI_S2),
    3: _make_sphere_table(3, _PI_S3),
    4: _make_sphere_table(4, _PI_S4),
    5: _make_sphere_table(5, _PI_S5),
    6: _make_sphere_table(6, _PI_S6),
    7: _make_sphere_table(7, _PI_S7),
}


# ── Complex projective spaces ────────────────────────────────────────────────
#
# CP^n is the orbit space S^{2n+1}/S^1.  For n ≥ 1:
#   π_1(CP^n) = 0
#   π_2(CP^n) = Z (the hyperplane class)
#   π_k(CP^n) = π_k(S^{2n+1}) for k ≥ 3
# This follows from the fibration S^1 → S^{2n+1} → CP^n and the long
# exact sequence (McGibbon 1980 §1).


def _pi_cp(n_param: int, k_max: int = 14) -> Dict[int, KnownHomotopyEntry]:
    out: Dict[int, KnownHomotopyEntry] = {1: _E()}  # π_1(CP^n) = 0
    out[2] = _E(free_rank=1, source="McGibbon1980")
    s_dim = 2 * n_param + 1
    sphere_table = {
        3: _PI_S3, 5: _PI_S5, 7: _PI_S7,
    }
    base = sphere_table.get(s_dim)
    for k in range(3, k_max + 1):
        if base is not None and k in base:
            e = base[k]
            out[k] = KnownHomotopyEntry(
                free_rank=e.free_rank,
                torsion=e.torsion,
                p_primary=dict(e.p_primary),
                source=f"derived from π_{k}(S^{s_dim}); {e.source}",
                confidence="derived",
            )
        else:
            # Without the sphere data we cannot back-derive; leave blank.
            continue
    return out


KNOWN_PI_N_CP: Dict[int, KnownHomotopyTable] = {
    1: KnownHomotopyTable(
        family="CP",
        parameter=1,
        entries={2: _E(free_rank=1, source="CP^1 = S^2"),
                 **{k: KnownHomotopyEntry(
                     free_rank=_PI_S2[k].free_rank,
                     torsion=_PI_S2[k].torsion,
                     p_primary=dict(_PI_S2[k].p_primary),
                     source=f"CP^1 = S^2; {_PI_S2[k].source}",
                     confidence="derived",
                 ) for k in _PI_S2 if k != 1}},
        n_min=1, n_max=14,
        notes="CP^1 ≅ S^2, so π_*(CP^1) = π_*(S^2).",
    ),
    2: KnownHomotopyTable(family="CP", parameter=2, entries=_pi_cp(2), n_min=1, n_max=14),
    3: KnownHomotopyTable(family="CP", parameter=3, entries=_pi_cp(3), n_min=1, n_max=14),
}


# ── Real projective spaces ───────────────────────────────────────────────────
#
# RP^n = S^n / ±1.  π_1(RP^n) = Z/2 for n ≥ 2, π_k(RP^n) = π_k(S^n) for k ≥ 2.
# (Standard via the double cover S^n → RP^n.)


def _pi_rp(n_param: int, k_max: int = 14) -> Dict[int, KnownHomotopyEntry]:
    sphere_table = {
        1: _PI_S1, 2: _PI_S2, 3: _PI_S3, 4: _PI_S4, 5: _PI_S5,
    }
    out: Dict[int, KnownHomotopyEntry] = {}
    if n_param >= 2:
        out[1] = _E(torsion=(2,), p_primary={2: (2,)}, source="RP^n double cover", confidence="derived")
    else:
        out[1] = _E(free_rank=1, source="RP^1 = S^1", confidence="derived")
    base = sphere_table.get(n_param)
    if base is None:
        return out
    for k in range(2, k_max + 1):
        if k not in base:
            continue
        e = base[k]
        out[k] = KnownHomotopyEntry(
            free_rank=e.free_rank,
            torsion=e.torsion,
            p_primary=dict(e.p_primary),
            source=f"π_{k}(RP^{n_param}) = π_{k}(S^{n_param}); {e.source}",
            confidence="derived",
        )
    return out


KNOWN_PI_N_RP: Dict[int, KnownHomotopyTable] = {
    n: KnownHomotopyTable(family="RP", parameter=n, entries=_pi_rp(n), n_min=1, n_max=14)
    for n in range(1, 6)
}


# ── Quaternionic projective spaces ────────────────────────────────────────────
#
# HP^n is the orbit space S^{4n+3}/S^3.  Standard facts:
#   π_1(HP^n) = π_2(HP^n) = π_3(HP^n) = 0
#   π_4(HP^n) = Z (the generator)
#   For k ≥ 5: long exact sequence of S^3 → S^{4n+3} → HP^n.
# HP^1 = S^4 (since the bundle S^3 → S^7 → S^4 is the Hopf fibration ν).


_PI_HP1: Dict[int, KnownHomotopyEntry] = {
    1: _E(),
    2: _E(),
    3: _E(),
    **{k: KnownHomotopyEntry(
        free_rank=_PI_S4[k].free_rank,
        torsion=_PI_S4[k].torsion,
        p_primary=dict(_PI_S4[k].p_primary),
        source=f"HP^1 = S^4; {_PI_S4[k].source}",
        confidence="derived",
    ) for k in _PI_S4 if k >= 4},
}


KNOWN_PI_N_HP: Dict[int, KnownHomotopyTable] = {
    1: KnownHomotopyTable(
        family="HP",
        parameter=1,
        entries=_PI_HP1,
        n_min=1,
        n_max=14,
        notes="HP^1 ≅ S^4 (quaternionic Hopf fibration).",
    ),
}


# ── Eilenberg-MacLane spaces ─────────────────────────────────────────────────
#
# K(A, n) has π_k(K(A, n)) = A if k = n, else 0. This is the defining
# property and the easiest "computation" of all.


def _pi_em(group_label: str, n_param: int, k_max: int = 14) -> Dict[int, KnownHomotopyEntry]:
    out: Dict[int, KnownHomotopyEntry] = {}
    for k in range(1, k_max + 1):
        if k != n_param:
            out[k] = _E(source=f"K({group_label}, {n_param}) defining property")
            continue
        if group_label == "Z":
            out[k] = _E(free_rank=1, source=f"K(Z, {n_param}) defining property")
        elif group_label.startswith("Z/"):
            d = int(group_label[2:])
            p, m = _smallest_prime_factor(d)
            p_primary = {p: (p**m,)} if d == p**m else {}
            if not p_primary:
                # Cyclic group of composite order — fall back to total torsion.
                p_primary = _torsion_to_p_primary([d])
            out[k] = _E(
                torsion=(d,),
                p_primary=p_primary,
                source=f"K({group_label}, {n_param}) defining property",
            )
    return out


def _smallest_prime_factor(n: int) -> Tuple[int, int]:
    """Return (p, k) where n = p^k for a prime p; raise if n is not a prime power."""
    if n < 2:
        return (2, 0)
    p = 2
    while p * p <= n:
        if n % p == 0:
            k = 0
            m = n
            while m % p == 0:
                m //= p
                k += 1
            if m == 1:
                return (p, k)
            return (p, 0)  # composite signal
        p += 1
    return (n, 1)  # n itself is prime


def _torsion_to_p_primary(invariant_factors) -> Dict[int, Tuple[int, ...]]:
    by_prime: Dict[int, List[int]] = {}
    for d in invariant_factors:
        m = int(d)
        p = 2
        while m > 1 and p * p <= m:
            if m % p == 0:
                e = 0
                while m % p == 0:
                    m //= p
                    e += 1
                by_prime.setdefault(p, []).append(p**e)
            else:
                p += 1
        if m > 1:
            by_prime.setdefault(m, []).append(m)
    return {p: tuple(sorted(v, reverse=True)) for p, v in by_prime.items()}


KNOWN_PI_N_EM: Dict[Tuple[str, int], KnownHomotopyTable] = {
    ("Z", 1): KnownHomotopyTable(
        family="EM_Z", parameter=1,
        entries=_pi_em("Z", 1),
        n_min=1, n_max=14,
        notes="K(Z, 1) = S^1.",
    ),
    ("Z", 2): KnownHomotopyTable(
        family="EM_Z", parameter=2,
        entries=_pi_em("Z", 2),
        n_min=1, n_max=14,
        notes="K(Z, 2) = CP^∞.",
    ),
    ("Z/2", 1): KnownHomotopyTable(
        family="EM_Zmod", parameter=1,
        entries=_pi_em("Z/2", 1),
        n_min=1, n_max=14,
        notes="K(Z/2, 1) = RP^∞.",
    ),
}


# ── Lookup helper ────────────────────────────────────────────────────────────


def lookup(family: str, parameter: Optional[int], n: int) -> Optional[KnownHomotopyEntry]:
    """Return the table entry for π_n of the requested space, or None.

    ``family`` is one of ``"S"``, ``"CP"``, ``"RP"``. ``parameter`` is the
    sphere/projective-space dimension parameter. ``n`` is the homotopy stem.

    None is returned when the family/parameter is unrecognized OR the
    specific stem ``n`` is outside the published range.
    """
    tables: Dict[str, Dict[int, KnownHomotopyTable]] = {
        "S": KNOWN_PI_N_SPHERES,
        "CP": KNOWN_PI_N_CP,
        "RP": KNOWN_PI_N_RP,
        "HP": KNOWN_PI_N_HP,
    }
    fam = tables.get(family)
    if fam is not None and parameter is not None:
        tab = fam.get(parameter)
        if tab is not None:
            return tab.entries.get(n)
    # K(A, m) family: family is "EM_Z" or "EM_Zmod", parameter is m.
    if family in ("EM_Z", "EM_Zmod") and parameter is not None:
        for (label, m), tab in KNOWN_PI_N_EM.items():
            if family == "EM_Z" and label == "Z" and m == parameter:
                return tab.entries.get(n)
            if family == "EM_Zmod" and label.startswith("Z/") and m == parameter:
                return tab.entries.get(n)
    return None


__all__ = [
    "KnownHomotopyEntry",
    "KnownHomotopyTable",
    "KNOWN_PI_N_SPHERES",
    "KNOWN_PI_N_CP",
    "KNOWN_PI_N_RP",
    "KNOWN_PI_N_HP",
    "KNOWN_PI_N_EM",
    "lookup",
]
