import numpy as np

def generate_lean_isomorphism_certificate(Q1: np.ndarray, Q2: np.ndarray, P: np.ndarray, theorem_name: str = "homeo_cert") -> str:
    """
    Generates a Lean 4 proof script verifying that P is an Algebraic Isomorphism Certificate
    between the intersection forms Q1 and Q2.
    
    This fulfills the Formal Verification requirement for Surgery Theory.
    
    Returns
    -------
    str
        The Lean 4 source code.
    """
    
    def matrix_to_lean(mat):
        rows = []
        for r in mat:
            row_str = "![" + ", ".join(map(str, r)) + "]"
            rows.append(row_str)
        return "![" + ",\n  ".join(rows) + "]"
        
    n = Q1.shape[0]
    
    lean_code = f"""import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant

-- Generated by pysurgery
-- Theorem: The forms Q1 and Q2 are isomorphic via P.

def Q1 : Matrix (Fin {n}) (Fin {n}) ℤ :=
  {matrix_to_lean(Q1)}

def Q2 : Matrix (Fin {n}) (Fin {n}) ℤ :=
  {matrix_to_lean(Q2)}

def P : Matrix (Fin {n}) (Fin {n}) ℤ :=
  {matrix_to_lean(P)}

theorem {theorem_name}_valid : Pᵀ * Q1 * P = Q2 := by
  -- native_decide compiles the check to native code, which is faster than `decide`
  -- for small matrices.  For larger matrices (n > ~4), consider replacing this
  -- with explicit norm_num or ring-based tactics for better scalability.
  native_decide

theorem {theorem_name}_unimodular : (P.det = 1) ∨ (P.det = -1) := by
  -- Evaluate determinant
  native_decide
"""
    return lean_code
