import numpy as np
import re
import shutil
import subprocess
import tempfile
from pydantic import BaseModel, ConfigDict


class LeanCheckResult(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    available: bool
    exit_code: int
    stdout: str
    stderr: str
    success: bool
    command: str


def run_lean_check(
    lean_code: str, lean_cmd: str = "lean", timeout_sec: int = 20
) -> LeanCheckResult:
    """Optionally run local Lean on generated code and return structured diagnostics."""
    exe = shutil.which(lean_cmd)
    if exe is None:
        return LeanCheckResult(
            available=False,
            exit_code=127,
            stdout="",
            stderr=f"Lean executable '{lean_cmd}' not found.",
            success=False,
            command=lean_cmd,
        )

    with tempfile.NamedTemporaryFile(mode="w", suffix=".lean", delete=False) as f:
        f.write(lean_code)
        lean_path = f.name

    proc = subprocess.run(
        [exe, lean_path],
        capture_output=True,
        text=True,
        timeout=timeout_sec,
    )
    return LeanCheckResult(
        available=True,
        exit_code=int(proc.returncode),
        stdout=proc.stdout,
        stderr=proc.stderr,
        success=(proc.returncode == 0),
        command=f"{exe} {lean_path}",
    )


def generate_lean_isomorphism_certificate(
    Q1: np.ndarray, Q2: np.ndarray, P: np.ndarray, theorem_name: str = "homeo_cert"
) -> str:
    """
    Generates a Lean 4 proof script verifying that P is an Algebraic Isomorphism Certificate
    between the intersection forms Q1 and Q2.

    This fulfills the Formal Verification requirement for Surgery Theory.

    Returns
    -------
    str
        The Lean 4 source code.
    """

    Q1 = np.asarray(Q1)
    Q2 = np.asarray(Q2)
    P = np.asarray(P)

    if Q1.ndim != 2 or Q2.ndim != 2 or P.ndim != 2:
        raise ValueError("Lean export expects 2D matrices.")
    if (
        Q1.shape[0] != Q1.shape[1]
        or Q2.shape[0] != Q2.shape[1]
        or P.shape[0] != P.shape[1]
    ):
        raise ValueError("Lean export expects square matrices.")
    if Q1.shape != Q2.shape or Q1.shape != P.shape:
        raise ValueError("Q1, Q2, and P must have identical square shape.")
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", theorem_name):
        raise ValueError("theorem_name must be a valid Lean identifier.")

    def matrix_to_lean(mat):
        rows = []
        for r in mat:
            vals = []
            for x in r:
                xi = int(x)
                if x != xi:
                    raise ValueError("Lean export expects integer matrices over Z.")
                vals.append(str(xi))
            row_str = "![" + ", ".join(vals) + "]"
            rows.append(row_str)
        return "![" + ",\n  ".join(rows) + "]"

    n = Q1.shape[0]

    tactic = "native_decide" if n > 4 else "decide"

    lean_code = f"""import Mathlib

-- Generated by pysurgery
-- Theorem: The forms Q1 and Q2 are isomorphic via P.

def Q1 : Matrix (Fin {n}) (Fin {n}) ℤ :=
  {matrix_to_lean(Q1)}

def Q2 : Matrix (Fin {n}) (Fin {n}) ℤ :=
  {matrix_to_lean(Q2)}

def P : Matrix (Fin {n}) (Fin {n}) ℤ :=
  {matrix_to_lean(P)}

theorem {theorem_name}_valid : Pᵀ * Q1 * P = Q2 := by
  -- The proof is by strict matrix evaluation (decide)
  {tactic}

theorem {theorem_name}_unimodular : (P.det = 1) ∨ (P.det = -1) := by
  -- Evaluate determinant
  {tactic}
"""
    return lean_code
