r"""Local homology at every simplex, and the homology-manifold certificate.

Overview:
    Everything here is computed on the COMPLEX, exactly, at every simplex: no point is
    sampled, no scale is swept, nothing is estimated. It complements
    ``SimplicialComplex.is_homology_manifold`` (which reads vertex links only) with the
    full, simplex-by-simplex certificate of the definition.

Key Concepts:
    - **Local homology from links.** For x in the open simplex sigma of dimension k,

          H_j(|K|, |K| - x)  =  H~_{j-k-1}( lk sigma )

      with reduced integer homology and the convention ``H~_{-1}(empty) = Z`` (the link
      of a maximal simplex is empty). So local homology is read off the links, and the
      links of all simplices are obtained in one pass from the maximal simplices of K:
      ``lk sigma`` is generated by ``tau - sigma`` over the maximal ``tau >= sigma``.
    - **Classification relative to a dimension n.** At an interior point of an
      n-manifold ``H_*(M, M - x) = H_*(R^n, R^n - 0)`` (Z in degree n, 0 elsewhere); at
      a boundary point it is 0. So, per simplex sigma of dimension k:

          sphere    H~_*(lk sigma) = H~_*(S^(n-k-1)) and dim(lk sigma) = n-k-1
          acyclic   H~_*(lk sigma) = 0, k < n, and lk sigma is pure of dimension n-k-1
          other     anything else -- a singular point of |K| as an n-dimensional object

      Two sheets crossing at a point, a pinch point, a branching (n-1)-face, a free
      face, a simplex of the wrong dimension: each lands where the computation puts it,
      not where a threshold does.
    - **The certificate is the definition, checked everywhere.**
      ``closed``: every simplex is ``sphere``.
      ``with boundary``: every simplex is ``sphere`` or ``acyclic``, the acyclic simplices
      form a subcomplex B, and B is itself a closed homology (n-1)-manifold (Mitchell,
      *Defining the boundary of a homology manifold*, Proc. AMS 110 (1990) -- a
      necessary condition, checked the same way). Local homology alone cannot tell a
      boundary point from the free end of a dangling edge (both have zero local
      homology), and a vertex link can have the homology of S^(n-1) without being a
      homology manifold itself -- which is why every simplex is checked and the
      boundary is checked for consistency, rather than vertex links alone.

What the certificate implies:
    - ``n <= 3``: a simplicial homology n-manifold (with boundary) is a PL n-manifold
      (with boundary). Links of simplices of a homology manifold are homology
      manifolds with sphere / acyclic homology, and in dimension <= 2 that forces the
      sphere / the disk (classification of surfaces). Recorded as
      ``implies_pl_manifold``.
    - ``n >= 4``: NOT implied. A vertex link can be a homology 3-sphere that is not S^3
      (Poincare's), and then the vertex has no Euclidean neighbourhood.

What this is not about:
    It is about |K|. Whether |K| reflects the data is the scale question
    (Niyogi-Smale-Weinberger, see ``pysurgery.geometry.scale_window``). Local homology
    is not a homotopy invariant: the nerve of a cover can have simplices above the
    ambient dimension, and then its local homology is that of the nerve, not of the
    union it is homotopy equivalent to.

Common Workflows:
    1. **Certify a mesh** -> ``certify_homology_manifold(K)`` (or
       ``K.certify_homology_manifold()``).
    2. **Locate singularities** -> ``singular_simplices(K, n)``.
    3. **Extract the boundary** -> ``homology_manifold_boundary(K, n)``.
    4. **Read local homology at a point** -> ``local_homology(K, sigma)``.

Coefficient Ring:
    Z, exactly (ranks and torsion). Julia and Python backends give identical results.
"""

from __future__ import annotations

import itertools
import warnings
from collections import defaultdict
from typing import TYPE_CHECKING, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
from pydantic import BaseModel, ConfigDict, Field

from ..algebra.sparse_elimination import reduced_homology_from_simplices
from ..bridge.julia_bridge import julia_engine

if TYPE_CHECKING:  # pragma: no cover
    from .complexes import SimplicialComplex

Simplex = Tuple[int, ...]
ReducedHomology = Dict[int, Tuple[int, List[int]]]

__all__ = [
    "LocalHomologyType",
    "PseudomanifoldReport",
    "HomologyManifoldCertificate",
    "maximal_simplices",
    "links_of",
    "link_reduced_homology",
    "local_homology",
    "classify_simplices",
    "pseudomanifold_report",
    "certify_homology_manifold",
    "homology_manifold_boundary",
    "singular_simplices",
]


# --------------------------------------------------------------------------- #
# result types
# --------------------------------------------------------------------------- #


class LocalHomologyType(BaseModel):
    """The local type of |K| at the points of one open simplex, relative to a dimension n.

    Attributes:
        simplex (tuple[int, ...]): The simplex (sorted vertex tuple).
        dim (int): Its dimension k.
        kind (str): ``"sphere"`` (interior point of a homology n-manifold),
            ``"acyclic"`` (boundary candidate) or ``"other"`` (singular) -- see the module
            docstring for the exact rule.
        link_reduced_homology (dict[int, tuple[int, list[int]]]): The nonzero reduced
            integer homology of ``lk(simplex)``, ``{degree: (rank, torsion)}``; degree -1
            appears exactly for the empty link.
        link_dimension (int): ``dim lk(simplex)`` (-1 for the empty link).
        link_pure (bool): Whether every maximal simplex of the link has dimension
            ``link_dimension``.
    """

    model_config = ConfigDict(frozen=True)

    simplex: Tuple[int, ...]
    dim: int
    kind: str
    link_reduced_homology: Dict[int, Tuple[int, List[int]]]
    link_dimension: int
    link_pure: bool

    def local_homology(self) -> ReducedHomology:
        """``H_j(|K|, |K| - x)`` for x in this open simplex, ``{j: (rank, torsion)}``.

        Returns:
            The nonzero local homology groups, shifted from the link's reduced homology by
            ``j = degree + dim + 1``.
        """
        return {d + self.dim + 1: (r, list(t)) for d, (r, t) in self.link_reduced_homology.items()}

    def __str__(self) -> str:
        lk = ", ".join(
            f"H~_{d}=" + ("Z^%d" % r if r else "0") + "".join(f"+Z/{t}" for t in tor)
            for d, (r, tor) in sorted(self.link_reduced_homology.items())
        ) or "acyclic"
        return f"{self.simplex} (dim {self.dim}): {self.kind}; link {lk}"


class PseudomanifoldReport(BaseModel):
    """The combinatorial pseudomanifold conditions at dimension n.

    Attributes:
        n (int): The dimension tested.
        pure (bool): K has dimension n and every simplex lies in an n-simplex.
        non_branching (bool): Every (n-1)-simplex lies in at most two n-simplices.
        strongly_connected (bool): The dual graph (n-simplices, adjacent across
            (n-1)-faces) is connected.
        n_top (int): Number of n-simplices.
        n_boundary_faces (int): (n-1)-simplices in exactly one n-simplex.
        max_cofacets (int): Largest number of n-simplices around one (n-1)-simplex.
        reason (str): Why the test could not run (empty when it did).
    """

    n: int
    pure: bool
    non_branching: bool
    strongly_connected: bool
    n_top: int
    n_boundary_faces: int
    max_cofacets: int
    reason: str = ""

    @property
    def is_pseudomanifold(self) -> bool:
        """Pure, non-branching and strongly connected."""
        return bool(self.pure and self.non_branching and self.strongly_connected)

    @property
    def is_closed_pseudomanifold(self) -> bool:
        """A pseudomanifold with no boundary (n-1)-faces."""
        return self.is_pseudomanifold and self.n_boundary_faces == 0


class HomologyManifoldCertificate(BaseModel):
    """Result of ``certify_homology_manifold``: the definition, checked at every simplex.

    Attributes:
        n (int): The dimension certified against.
        is_closed_homology_manifold (bool): Every simplex has a sphere link.
        is_homology_manifold_with_boundary (bool): Every simplex is sphere or acyclic, the
            acyclic simplices form a subcomplex, and that subcomplex is a closed homology
            (n-1)-manifold. True also for closed manifolds (empty boundary).
        implies_pl_manifold (bool): ``n <= 3`` and one of the above -- then |K| is a PL
            n-manifold (with boundary).
        n_simplices (int): Number of simplices checked (all of them).
        n_sphere (int): Simplices with sphere links.
        n_acyclic (int): Simplices with acyclic links of the right dimension.
        n_other (int): Singular simplices.
        singular (list[LocalHomologyType]): Where the certificate fails.
        boundary (list[tuple[int, ...]]): The acyclic simplices.
        pseudomanifold (PseudomanifoldReport): The combinatorial conditions.
        notes (list[str]): Human-readable reasons for every failure.
        exact (bool): Always True -- integer homology of every link.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    n: int
    is_closed_homology_manifold: bool
    is_homology_manifold_with_boundary: bool
    implies_pl_manifold: bool
    n_simplices: int
    n_sphere: int
    n_acyclic: int
    n_other: int
    singular: List[LocalHomologyType] = Field(default_factory=list)
    boundary: List[Tuple[int, ...]] = Field(default_factory=list)
    pseudomanifold: Optional[PseudomanifoldReport] = None
    notes: List[str] = Field(default_factory=list)
    exact: bool = True

    @property
    def singular_vertices(self) -> List[int]:
        """Vertices whose own link is singular."""
        return [t.simplex[0] for t in self.singular if t.dim == 0]

    def __str__(self) -> str:
        if self.is_closed_homology_manifold:
            head = f"closed homology {self.n}-manifold"
        elif self.is_homology_manifold_with_boundary:
            head = (
                f"homology {self.n}-manifold WITH boundary "
                f"({len(self.boundary)} boundary simplices)"
            )
        else:
            head = f"NOT a homology {self.n}-manifold ({len(self.singular)} singular simplices)"
        tail = " -- hence a PL manifold (n <= 3)" if self.implies_pl_manifold else ""
        return (
            f"[n={self.n}] {head}{tail}; checked all {self.n_simplices} simplices"
            + "".join("\n  " + s for s in self.notes)
        )


# --------------------------------------------------------------------------- #
# links
# --------------------------------------------------------------------------- #


def _all_simplices(K: "SimplicialComplex") -> List[Simplex]:
    return [tuple(int(v) for v in s) for d in K.dimensions for s in K.n_simplices(d)]


def maximal_simplices(K: "SimplicialComplex") -> List[Simplex]:
    """The maximal simplices (facets) of K: those that are a face of nothing larger.

    Args:
        K: A simplicial complex (closed under faces).

    Returns:
        The maximal simplices, sorted by dimension then lexicographically.
    """
    non_max = set()
    for d in K.dimensions:
        if d < 1:
            continue
        for s in K.n_simplices(d):
            for i in range(len(s)):
                non_max.add(tuple(s[:i]) + tuple(s[i + 1:]))
    return sorted((s for s in _all_simplices(K) if s not in non_max), key=lambda s: (len(s), s))


def links_of(K: "SimplicialComplex", sigmas: Iterable[Iterable[int]]) -> Dict[Simplex, List[Simplex]]:
    """The maximal simplices of ``lk(sigma)`` for every sigma, in one pass.

    What is Being Computed?:
        ``lk(sigma) = {tau - sigma : sigma <= tau in K}``; its maximal simplices are
        exactly ``tau - sigma`` for the maximal ``tau >= sigma`` (two distinct maximal
        simplices containing sigma give distinct, incomparable differences).

    Args:
        K: A simplicial complex.
        sigmas: The simplices whose links are wanted (each must be in K).

    Returns:
        ``{sigma: [maximal simplices of lk(sigma)]}``; an empty list is the empty link.

    Raises:
        ValueError: If some sigma is not a simplex of K.
    """
    targets = [tuple(sorted(int(v) for v in s)) for s in sigmas]
    present = {d: set(K.n_simplices(d)) for d in K.dimensions}
    for s in targets:
        if s not in present.get(len(s) - 1, ()):
            raise ValueError(f"{s} is not a simplex of the complex")
    by_vertex: Dict[int, List[Simplex]] = defaultdict(list)
    for tau in maximal_simplices(K):
        for v in tau:
            by_vertex[v].append(tau)
    out: Dict[Simplex, List[Simplex]] = {}
    for s in targets:
        ss = set(s)
        gens = []
        for tau in by_vertex[s[0]]:
            if ss.issubset(tau):
                rest = tuple(v for v in tau if v not in ss)
                if rest:
                    gens.append(rest)
        out[s] = gens
    return out


def _flat(simplices: Sequence[Simplex]) -> Tuple[np.ndarray, np.ndarray]:
    flat = np.fromiter((v for s in simplices for v in s), dtype=np.int64)
    offsets = np.zeros(len(simplices) + 1, dtype=np.int64)
    np.cumsum([len(s) for s in simplices], out=offsets[1:])
    return flat, offsets


def _link_data(
    K: "SimplicialComplex", targets: List[Simplex], backend: str
) -> Dict[Simplex, Tuple[ReducedHomology, int, bool]]:
    """Reduced homology, dimension and purity of every target's link."""
    backend_norm = str(backend).lower().strip()
    use_julia = backend_norm == "julia" or (backend_norm == "auto" and julia_engine.available)
    if use_julia and targets:
        try:
            flat, offsets = _flat(_all_simplices(K))
            tflat, toffsets = _flat(targets)
            res = julia_engine.classify_simplex_links(flat, offsets, tflat, toffsets)
            return dict(zip(targets, res))
        except Exception as e:  # pragma: no cover - depends on the Julia runtime
            if backend_norm == "julia":
                raise
            warnings.warn(f"Julia link classification failed ({e!r}); falling back to Python.")
    links = links_of(K, targets)
    out = {}
    for s in targets:
        gens = links[s]
        red, ldim = reduced_homology_from_simplices(gens)
        pure = all(len(g) - 1 == ldim for g in gens)
        out[s] = (red, ldim, pure)
    return out


def link_reduced_homology(
    K: "SimplicialComplex", sigma: Iterable[int], backend: str = "auto"
) -> ReducedHomology:
    """Reduced integer homology of ``lk(sigma)``, degree -1 included.

    Args:
        K: A simplicial complex.
        sigma: A simplex of K.
        backend: 'auto', 'julia' or 'python'.

    Returns:
        ``{degree: (rank, torsion)}`` for the nonzero groups; ``{-1: (1, [])}`` when
        sigma is maximal (empty link).
    """
    s = tuple(sorted(int(v) for v in sigma))
    return _link_data(K, [s], backend)[s][0]


def local_homology(
    K: "SimplicialComplex", sigma: Iterable[int], backend: str = "auto"
) -> ReducedHomology:
    """Local homology ``H_j(|K|, |K| - x)`` for x in the open simplex sigma, exactly.

    What is Being Computed?:
        ``H_j(|K|, |K| - x) = H~_{j-k-1}(lk sigma)``, k = dim sigma (Munkres,
        *Elements of Algebraic Topology*, Lemma 63.1).

    Args:
        K: A simplicial complex.
        sigma: A simplex of K.
        backend: 'auto', 'julia' or 'python'.

    Returns:
        ``{j: (rank, torsion)}`` for the nonzero groups.

    Example:
        >>> # interior point of a triangulated surface: Z in degree 2
        >>> local_homology(sphere, (0,))
        {2: (1, [])}
    """
    s = tuple(sorted(int(v) for v in sigma))
    k = len(s) - 1
    return {d + k + 1: (r, list(t)) for d, (r, t) in link_reduced_homology(K, s, backend).items()}


# --------------------------------------------------------------------------- #
# classification
# --------------------------------------------------------------------------- #


def _kind(k: int, n: int, red: ReducedHomology, ldim: int, pure: bool) -> str:
    want = n - k - 1
    summary = {d: (r, tuple(t)) for d, (r, t) in red.items() if r or t}
    if summary == {want: (1, ())} and ldim == want:
        return "sphere"
    if not summary and k < n and ldim == want and pure:
        return "acyclic"
    return "other"


def classify_simplices(
    K: "SimplicialComplex",
    n: int,
    simplices: Optional[Iterable[Iterable[int]]] = None,
    backend: str = "auto",
) -> Dict[Simplex, LocalHomologyType]:
    """``sphere`` / ``acyclic`` / ``other`` relative to dimension n, at every simplex.

    What is Being Computed?:
        The local type of |K| at each open simplex (the rule is in the module
        docstring), from the exact integer reduced homology of its link.

    Algorithm:
        1. Links of all targets from the maximal simplices, in one pass.
        2. Reduced homology of every link by exact unimodular elimination (Python) or by
           the threaded ``classify_simplex_links_jl`` kernel (Julia).
        3. Compare with ``H~_*(S^(n-k-1))`` and with the link's dimension and purity.

    Args:
        K: A simplicial complex.
        n: The dimension to classify against.
        simplices: Restrict to these simplices (default: every simplex of K).
        backend: 'auto', 'julia' or 'python'.

    Returns:
        ``{simplex: LocalHomologyType}``.
    """
    n = int(n)
    targets = (
        _all_simplices(K)
        if simplices is None
        else [tuple(sorted(int(v) for v in s)) for s in simplices]
    )
    data = _link_data(K, targets, backend)
    out: Dict[Simplex, LocalHomologyType] = {}
    for s in targets:
        red, ldim, pure = data[s]
        k = len(s) - 1
        out[s] = LocalHomologyType(
            simplex=s,
            dim=k,
            kind=_kind(k, n, red, ldim, pure),
            link_reduced_homology={int(d): (int(r), [int(x) for x in t]) for d, (r, t) in red.items()},
            link_dimension=int(ldim),
            link_pure=bool(pure),
        )
    return out


def pseudomanifold_report(K: "SimplicialComplex", n: Optional[int] = None) -> PseudomanifoldReport:
    """The combinatorial conditions: pure n-dimensional, non-branching, strongly connected.

    Args:
        K: A simplicial complex.
        n: The dimension (default ``K.dimension``).

    Returns:
        A ``PseudomanifoldReport``.
    """
    n = K.dimension if n is None else int(n)
    top = list(K.n_simplices(n)) if n >= 0 else []
    if not top:
        return PseudomanifoldReport(
            n=n, pure=False, non_branching=False, strongly_connected=False, n_top=0,
            n_boundary_faces=0, max_cofacets=0, reason=f"no simplices of dimension {n}",
        )
    owners: Dict[Simplex, List[int]] = {}
    if n >= 1:
        owners = {tuple(f): [] for f in K.n_simplices(n - 1)}
        for idx, s in enumerate(top):
            for i in range(len(s)):
                owners.setdefault(tuple(s[:i]) + tuple(s[i + 1:]), []).append(idx)
    counts = [len(v) for v in owners.values()]
    covered = set()
    for s in top:
        for r in range(1, len(s) + 1):
            covered.update(itertools.combinations(s, r))
    pure = K.dimension == n and all(tuple(s) in covered for s in _all_simplices(K))
    adj: Dict[int, set] = {i: set() for i in range(len(top))}
    for own in owners.values():
        for a in own:
            adj[a].update(b for b in own if b != a)
    seen, stack = {0}, [0]
    while stack:
        u = stack.pop()
        for w in adj[u]:
            if w not in seen:
                seen.add(w)
                stack.append(w)
    return PseudomanifoldReport(
        n=n,
        pure=bool(pure),
        non_branching=all(c <= 2 for c in counts),
        strongly_connected=len(seen) == len(top),
        n_top=len(top),
        n_boundary_faces=sum(1 for c in counts if c == 1),
        max_cofacets=max(counts) if counts else 0,
    )


def _faces(s: Simplex) -> List[Simplex]:
    return [s[:i] + s[i + 1:] for i in range(len(s))] if len(s) > 1 else []


def certify_homology_manifold(
    K: "SimplicialComplex", n: Optional[int] = None, backend: str = "auto"
) -> HomologyManifoldCertificate:
    """Is K a homology n-manifold, closed or with boundary? Every simplex is checked.

    What is Being Computed?:
        The definition of a (simplicial) homology n-manifold with boundary, verified at
        every simplex from exact local homology, plus the consistency of the boundary
        (it must be a subcomplex and a closed homology (n-1)-manifold, certified
        recursively the same way).

    Algorithm:
        1. ``classify_simplices(K, n)`` at every simplex.
        2. ``closed`` iff every simplex is ``sphere``.
        3. ``with boundary`` iff there is no ``other`` simplex, the ``acyclic`` simplices
           are closed under taking faces (otherwise a zero local homology marks a
           dangling piece or a pinched rim, not a boundary), and they form a closed
           homology (n-1)-manifold.

    Preserved Invariants:
        Exact integer homology throughout; the Julia and Python backends agree.

    Args:
        K: A simplicial complex.
        n: The dimension to certify against (default ``K.dimension``).
        backend: 'auto', 'julia' or 'python'.

    Returns:
        A ``HomologyManifoldCertificate``.

    Use When:
        - ``is_homology_manifold`` (vertex links only) is not enough: in dimension >= 3
          a vertex link can have sphere homology without being a homology manifold.
        - Locating the singular set of a reconstructed complex.

    Example:
        >>> cert = certify_homology_manifold(K)
        >>> cert.is_closed_homology_manifold, cert.implies_pl_manifold
        (True, True)
    """
    from .complexes import SimplicialComplex

    n = K.dimension if n is None else int(n)
    types = classify_simplices(K, n, backend=backend)
    other = [t for t in types.values() if t.kind == "other"]
    acyc = {s for s, t in types.items() if t.kind == "acyclic"}
    notes: List[str] = []
    bad = {t.simplex for t in other}
    if other:
        notes.append(
            f"{len(other)} simplex(es) whose link is neither a homology (n-k-1)-sphere "
            f"nor acyclic of dimension n-k-1"
        )
    with_boundary = bool(types) and not other
    if acyc and with_boundary:
        not_closed = sorted({s for s in acyc for f in _faces(s) if f not in acyc})
        if not_closed:
            with_boundary = False
            bad.update(not_closed)
            bad.update(f for s in not_closed for f in _faces(s) if f not in acyc)
            notes.append(
                f"the acyclic simplices are not closed under faces at {len(not_closed)} "
                f"simplex(es): local homology is zero there without it being a boundary "
                f"(a dangling piece, a pinched rim)"
            )
        else:
            B = SimplicialComplex.from_simplices(sorted(acyc), close_under_faces=True)
            cb = certify_homology_manifold(B, n - 1, backend=backend) if n >= 1 else None
            if cb is not None and not cb.is_closed_homology_manifold:
                with_boundary = False
                bad.update(t.simplex for t in cb.singular)
                notes.append(f"the boundary is not a closed homology {n - 1}-manifold")
    closed = bool(types) and not acyc and not other
    sing = sorted((types[s] for s in bad if s in types), key=lambda t: (t.dim, t.simplex))
    if n >= 4 and with_boundary:
        notes.append(
            f"n = {n} >= 4: a homology manifold need not be a topological manifold -- a "
            f"vertex link can be a homology sphere that is not a sphere"
        )
    sv = sorted({t.simplex[0] for t in sing if t.dim == 0})
    if sv:
        notes.append(f"{len(sv)} singular vertex(es): {sv[:20]}{' ...' if len(sv) > 20 else ''}")
    return HomologyManifoldCertificate(
        n=n,
        is_closed_homology_manifold=closed,
        is_homology_manifold_with_boundary=with_boundary,
        implies_pl_manifold=bool(with_boundary and n <= 3),
        n_simplices=len(types),
        n_sphere=sum(t.kind == "sphere" for t in types.values()),
        n_acyclic=len(acyc),
        n_other=len(other),
        singular=sing,
        boundary=sorted(acyc, key=lambda s: (len(s), s)),
        pseudomanifold=pseudomanifold_report(K, n),
        notes=notes,
    )


def homology_manifold_boundary(
    K: "SimplicialComplex", n: Optional[int] = None, backend: str = "auto"
) -> "SimplicialComplex":
    """The boundary of a homology n-manifold with boundary, as a complex.

    Refuses when K is not one: then "the simplices with zero local homology" is not a
    boundary of anything, and returning it would mislabel the free ends of dangling
    pieces as boundary.

    Args:
        K: A simplicial complex.
        n: The dimension (default ``K.dimension``).
        backend: 'auto', 'julia' or 'python'.

    Returns:
        The boundary subcomplex (empty for a closed manifold).

    Raises:
        NotAManifoldError: If K is not a homology n-manifold with boundary.
    """
    from ..core.exceptions import NotAManifoldError
    from .complexes import SimplicialComplex

    c = certify_homology_manifold(K, n, backend=backend)
    if not c.is_homology_manifold_with_boundary:
        raise NotAManifoldError(
            f"not a homology {c.n}-manifold with boundary: " + "; ".join(c.notes)
        )
    return SimplicialComplex.from_simplices(c.boundary, close_under_faces=True)


def singular_simplices(
    K: "SimplicialComplex", n: Optional[int] = None, backend: str = "auto"
) -> List[LocalHomologyType]:
    """Where |K| fails to be a homology n-manifold (with boundary), exactly.

    Args:
        K: A simplicial complex.
        n: The dimension (default ``K.dimension``).
        backend: 'auto', 'julia' or 'python'.

    Returns:
        The singular simplices with their local types, sorted by dimension.
    """
    return certify_homology_manifold(K, n, backend=backend).singular
